name: Generate PDF release notes

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Deployment?"
        default: "Suprema"
      version:
        description: "Version of the release"
        required: true
      date:
        description: "Release date"
        required: true

permissions:
  contents: write

env:
  PRINCE_VER: 16

jobs:
  build-n-deploy:
    name: Generate PDF
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Print Input
      run: |
        echo "Input version: ${{ github.event.inputs.version }}"
        echo "Input date: ${{ github.event.inputs.date }}"

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Install Prince
      run: |
        curl https://www.princexml.com/download/prince-${{ env.PRINCE_VER }}-macos.zip -O
        tar zxf prince-${{ env.PRINCE_VER }}-macos.zip
        cd prince-${{ env.PRINCE_VER }}-macos
        yes "" | sudo ./install.sh

    - name: Install pdfcpu
      run: brew install pdfcpu

    - name: Build PDF
      run: |
        node generatepdf -u "https://supremainc.github.io/biostar2-docs/cover/biostar2" --prince-args="--page-size='a4' --style=./print.css --javascript" -o ./pdf/BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_KO_${{ github.event.inputs.date }}.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_KO_${{ github.event.inputs.date }}.pdf
        pdfcpu merge -mode append ./pdf/BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_KO_${{ github.event.inputs.date }}.pdf back-cover.pdf
        node generatepdf -u "https://supremainc.github.io/biostar2-docs/en/cover/biostar2" --prince-args="--page-size='a4' --style=./print.css --javascript" -o ./pdf/BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_EN_${{ github.event.inputs.date }}.pdf --dest ./pdf --include-index
        pdfcpu annot remove -pages 1 ./pdf/BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_EN_${{ github.event.inputs.date }}.pdf
        pdfcpu merge -mode append ./pdf/BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_EN_${{ github.event.inputs.date }}.pdf back-cover-en.pdf
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.event.inputs.version }}" # 생성할 Release의 태그 이름
        release_name: "v${{ github.event.inputs.version }}"
        body: "Suprema Release Note v${{ github.event.inputs.version }}"
        draft: false
        prerelease: false
    
    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_KO_${{ github.event.inputs.date }}.pdf
        asset_name: BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_KO_${{ github.event.inputs.date }}.pdf
        asset_content_type: application/pdf

    - name: Upload to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: pdf/BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_EN_${{ github.event.inputs.date }}.pdf
        asset_name: BioStar_2_RevisionNotes_${{ github.event.inputs.version }}_EN_${{ github.event.inputs.date }}.pdf
        asset_content_type: application/pdf